language: node_js
sudo: false
node_js:
  - "11"
  - "8"
install:
  - npm install
  - npm install codecov
script:
  - npm run build
  - npm run test:coverage
after_success:
  - npx codecov

before_deploy:
  # HACK: Delete "build" from gitignore for deployment because github pages works with `git add --all`
  - cat .gitignore | grep -v "build" > .gitignore.without.build.tmp
  - cat .gitignore.without.build.tmp > .gitignore
  - rm .gitignore.without.build.tmp
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: 27-As-a-user-I-want-a-deployed-app # TODO #27 change to master after successful test deployment
