sudo: false
language: node_js
node_js:
  - "11"
  - "8"

services:
  - docker

env:
  - PROJECT=parvenu DOCKER_REPO=parvenu

install:
  - npm install
  - npm install codecov
script:
  - npm run build
  - npm run test:coverage
after_success:
  - npx codecov

before_deploy:
  # HACK: Delete "build" from gitignore because github pages uses `git add --all`
  - ./deployment/delete-build-dir-from-gitignore.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of travis repository, as a secure variable
  keep_history: true
  on:
    branch: master

after_deploy:
  - ./deployment/push-to-docker-hub.sh
