language: node_js
sudo: false
node_js:
  - "11"
  - "8"
install:
  - npm install
  - npm install codecov
script:
  - npm run build
  - npm run test:coverage
after_success:
  - npx codecov

before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: 27-As-a-user-I-want-a-deployed-app # TODO #27 change to master after successful test deployment
